# Generated by Django 6.0 on 2025-12-08 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ROIDistribution',
            fields=[
                ('roi_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=20)),
                ('roi_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
