# Generated by Django 6.0 on 2025-12-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roidistribution',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roi_records', to='investments.investment'),
        ),
    ]
