# Generated by Django 4.1.7 on 2025-12-09 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(default=uuid.uuid4, max_length=20, unique=True)),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(default=uuid.uuid4, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible'), ('Admitted', 'Admitted')], default='In Progress', max_length=20)),
                ('merit_score', models.FloatField(blank=True, null=True)),
                ('eligibility_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(default=uuid.uuid4, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_id', models.CharField(max_length=20, unique=True)),
                ('program_name', models.CharField(max_length=100)),
                ('cutoff_score', models.FloatField()),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=20, unique=True)),
                ('semester_no', models.IntegerField()),
                ('section_name', models.CharField(max_length=50)),
                ('available_seats', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.program')),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('waitlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_no', models.IntegerField()),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Admitted', 'Admitted')], default='Waiting', max_length=20)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admission')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('timetable_id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.section')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(default=uuid.uuid4, max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admission')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('scholarship_id', models.AutoField(primary_key=True, serialize=False)),
                ('waiver_percentage', models.IntegerField()),
                ('scholarship_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Approval', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_id', models.CharField(default=uuid.uuid4, max_length=20, unique=True)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.applicant')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentRecord',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admission')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('file_url', models.URLField()),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.applicant')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='program_applied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.program'),
        ),
        migrations.AddField(
            model_name='admission',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admissions.applicant'),
        ),
        migrations.AddField(
            model_name='admission',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.program'),
        ),
        migrations.AddField(
            model_name='admission',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.section'),
        ),
    ]
