# Generated by Django 4.1.7 on 2025-12-09 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
