# Generated by Django 4.1.7 on 2025-12-09 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_faculty_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='student_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicant_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='interview_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='invoice_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
